language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: v1
  target_branch: gh-pages